name: Test Workflow
on:
  push:
    branches: [main]
  workflow_dispatch: # manually launch
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker://node:18
    steps:
      - uses: actions/checkout@v4
      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"
