name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # cloning the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # configuring Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # executing tests
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pip install pytest
          pytest tests/

      # configuring Docker Buildx to build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # connecting to the Github Container Registry
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # building and pushing the Docker image
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            PYTHON_VERSION=3.11
